class Box{
	public static void main (String[] args){
		String color0 = "Purple";
		String color1 = "Red";
		String color2 = "Blue";
		String color3 = "Green";
		String color4 = "White";
		String color5 = "Yellow";
		String color6 = "Pink";
		String color7 = "Grey";
		String color8 = "Maroon";
		String color9 = "Sky Blue";
		String color10 = "Parrot Green";
		String color11 = "Gold";
		String color12 = "Silver";
		String color13 = "Violet";
		String color14 = "Peach";
		String color15 = "Mint";
		String color16 = "Lavender";
		String color17 = "Navy";
		String color18 = "Lime Yellow";
		String color19 = "Magenta";
		String color20 = "Cyan";
		String color21 = "DarkBlue";
		String color22 = "Black";
		String color23 = "Dark Green";
		String color24 = "Brown";
		String color25 = "Brick Red";
		String color26 = "Light Pink";
		String color27 = "Musturd";
		String color28 = "Bronze";
		String color29 = "Tomato Red";
		
		String[] colors ={color0,color1,color2,color3,color4,color5,color6,color7,
		color8,color9,color8,color9,color10,color11,color12,color13,color14,color15,
		color16,color17,color18,color19,color20,color21,color22,color23,color24,color25,
		color26,color27,color28,color29};
//String ref = colors[23];	
   		System.out.println("Index point 1:" + colors[0]);
        System.out.println("Index point 2:" + colors[1]);
		System.out.println("Index point 3:" + colors[2]);
		System.out.println("Index point 4:" + colors[3]);
	    System.out.println("Index point 5:" + colors[4]);
        System.out.println("Index point 6:" + colors[5]);
		System.out.println("Index point 7:" + colors[6]);
		System.out.println("Index point 8:" + colors[7]);
		System.out.println("Index point 9:" + colors[8]);
        System.out.println("Index point 10:" + colors[9]);
		System.out.println("Index point 11:" + colors[10]);
		System.out.println("Index point 12:" + colors[11]);
	    System.out.println("Index point 13:" + colors[12]);
        System.out.println("Index point 14:" + colors[13]);
		System.out.println("Index point 15:" + colors[14]);
		System.out.println("Index point 16:" + colors[15]);
		System.out.println("Index point 17:" + colors[16]);
        System.out.println("Index point 18:" + colors[17]);
		System.out.println("Index point 19:" + colors[18]);
		System.out.println("Index point 20:" + colors[19]);
	    System.out.println("Index point 21:" + colors[20]);
        System.out.println("Index point 22:" + colors[21]);
		System.out.println("Index point 23:" + colors[22]);
		System.out.println("Index point 24:" + colors[23]);
		System.out.println("Index point 25:" + colors[24]);
        System.out.println("Index point 26:" + colors[25]);
		System.out.println("Index point 27:" + colors[26]);
		System.out.println("Index point 28:" + colors[27]);
	    System.out.println("Index point 29:" + colors[28]);
        System.out.println("Index point 30:" + colors[29]);
		
		System.out.println("-----------------------------");
        colors[0]= "Amber";
		colors[1]= "Aquamarine"; 
		colors[2]= "Beige"; 
		colors[3]= "Burgundy"; 
		colors[4]= "Charcoal";
		colors[5]= "Coral";
		colors[6]= "Emerald";
        colors[7]= "Fuchsia";
		colors[8]= "Indigo";
		colors[9]= "Ivory";
		colors[10]= "Jade";
		colors[11]= "Khaki";
		colors[12]= "Lilac";
		colors[13]= "Lime";
		colors[14]= "Mauve";
        colors[15]= "Mustard";
		colors[16]= "Olive Green";
		colors[17]= "Orchid";
		colors[18]= "Periwinkle";
		colors[19]= "Platinum";
		colors[20]= "Raspberry";
		colors[21]= "Rose Gold";
		colors[22]= "Ruby";
        colors[23]= "Saffron";
		colors[24]= "Sapphire";
		colors[25]= "Scarlet";
		colors[26]= "Teal";
		colors[27]= "Tangerine";
		colors[28]= "Ultramarine";
		 colors[29]= "Crimson";
		System.out.println("Index point 1:" + colors[0]);
        System.out.println("Index point 2:" + colors[1]);
		System.out.println("Index point 3:" + colors[2]);
		System.out.println("Index point 4:" + colors[3]);
	    System.out.println("Index point 5:" + colors[4]);
        System.out.println("Index point 6:" + colors[5]);
		System.out.println("Index point 7:" + colors[6]);
		System.out.println("Index point 8:" + colors[7]);
		System.out.println("Index point 9:" + colors[8]);
        System.out.println("Index point 10:" + colors[9]);
		System.out.println("Index point 11:" + colors[10]);
		System.out.println("Index point 12:" + colors[11]);
	    System.out.println("Index point 13:" + colors[12]);
        System.out.println("Index point 14:" + colors[13]);
		System.out.println("Index point 15:" + colors[14]);
		System.out.println("Index point 16:" + colors[15]);
		System.out.println("Index point 17:" + colors[16]);
        System.out.println("Index point 18:" + colors[17]);
		System.out.println("Index point 19:" + colors[18]);
		System.out.println("Index point 20:" + colors[19]);
	    System.out.println("Index point 21:" + colors[20]);
        System.out.println("Index point 22:" + colors[21]);
		System.out.println("Index point 23:" + colors[22]);
		System.out.println("Index point 24:" + colors[23]);
		System.out.println("Index point 25:" + colors[24]);
        System.out.println("Index point 26:" + colors[25]);
		System.out.println("Index point 27:" + colors[26]);
		System.out.println("Index point 28:" + colors[27]);
	    System.out.println("Index point 29:" + colors[28]);
        System.out.println("Index point 30:" + colors[29]);
    }
}
class Cloth{
	public static void main(String[] args){
		String cloth0 = "Skirt";
		String cloth1 = "Shirt";
		String cloth2= "T-Shirt"; 
		String cloth3 = "Jeans";
		String cloth4 = "Trouser"; 
		String cloth5 = "Shorts"; 
		String cloth6 = "Jacket"; 
		String cloth7 = "Sweater"; 
		String cloth8 = "Hoodie";
        String cloth9 = "Blazer"; 
		String cloth10 = "Coat" ; 
		String cloth11 = "Leggings"; 
		String cloth12 = "Kurta";
		String cloth13 = "Saree"; 
		String cloth14 = "Innerwear"; 
		String cloth15 = "Nightwear";
        String cloth16 = "Track Pants"; 
		String cloth17 = "Dungarees"; 
		String cloth18 = "Salwar"; 
		String cloth19 = "Chinos"; 
		String cloth20 = "Cargo Pants"; 
		String cloth21 = "Socks"; 
		String cloth22 = "Scarf";
	    String cloth23 = "Gloves"; 
		String cloth24 = "Swimwear";
		String[] cloth = { cloth0,cloth1,cloth2,cloth3,cloth4,cloth5,cloth6,cloth7,
		cloth8,cloth9,cloth8,cloth9,cloth10,cloth11,cloth12,cloth13,cloth14,cloth15,
		cloth16,cloth17,cloth18,cloth19,cloth20,cloth21,cloth22,cloth23,cloth24};
		System.out.println("Index point 1:" + cloth[0]);
        System.out.println("Index point 2:" + cloth[1]);
		System.out.println("Index point 3:" + cloth[2]);
		System.out.println("Index point 4:" + cloth[3]);
	    System.out.println("Index point 5:" + cloth[4]);
        System.out.println("Index point 6:" +cloth[5]);
		System.out.println("Index point 7:" + cloth[6]);
		System.out.println("Index point 8:" + cloth[7]);
		System.out.println("Index point 9:" + cloth[8]);
        System.out.println("Index point 10:" + cloth[9]);
		System.out.println("Index point 11:" + cloth[10]);
		System.out.println("Index point 12:" + cloth[11]);
	    System.out.println("Index point 13:" + cloth[12]);
        System.out.println("Index point 14:" + cloth[13]);
		System.out.println("Index point 15:" + cloth[14]);
		System.out.println("Index point 16:" + cloth[15]);
		System.out.println("Index point 17:" + cloth[16]);
        System.out.println("Index point 18:" + cloth[17]);
		System.out.println("Index point 19:" + cloth[18]);
		System.out.println("Index point 20:" + cloth[19]);
	    System.out.println("Index point 21:" + cloth[20]);
        System.out.println("Index point 22:" + cloth[21]);
		System.out.println("Index point 23:" + cloth[22]);
		System.out.println("Index point 24:" + cloth[23]);
		System.out.println("Index point 25:" + cloth[24]);
		System.out.println("-----------------------------");
        cloth[0]= "Denim Jacket";
		cloth[1]= "Windbreaker"; 
        cloth[2]= "Puffer Jacket";
		cloth[3]= "Overcoat"; 
        cloth[4]="Tank Top";
		cloth[5]= "Maternity Wear";
		cloth[6]= "Bathrobe";       
		cloth[7]= "Gown";
		cloth[8]= "Culottes"; 
        cloth[9]="Halter Top";
        cloth[10]= " Polo Shirt";
		cloth[11]= "Bolero Jacket";
        cloth[12]= "Kimono";
		cloth[13]= "Tunic"; 
        cloth[14]="Bodysuit";
        cloth[15]= "Poncho";
		cloth[16]= "Anorak"; 
        cloth[17]= "Peacoat";
		cloth[18]= "Romper"; 
        cloth[19]="Jumpsuit";
        cloth[20]= "Beige";
        cloth[21]= "Corduroy Pants"; 
		cloth[22]= "Burgundy"; 		
		cloth[23]= "Capri Pants"; 
		cloth[24]= "Vest";
        System.out.println("Index point 1:" + cloth[0]);
        System.out.println("Index point 2:" + cloth[1]);
		System.out.println("Index point 3:" + cloth[2]);
		System.out.println("Index point 4:" + cloth[3]);
	    System.out.println("Index point 5:" + cloth[4]);
        System.out.println("Index point 6:" +cloth[5]);
		System.out.println("Index point 7:" + cloth[6]);
		System.out.println("Index point 8:" + cloth[7]);
		System.out.println("Index point 9:" + cloth[8]);
        System.out.println("Index point 10:" + cloth[9]);
		System.out.println("Index point 11:" + cloth[10]);
		System.out.println("Index point 12:" + cloth[11]);
	    System.out.println("Index point 13:" + cloth[12]);
        System.out.println("Index point 14:" + cloth[13]);
		System.out.println("Index point 15:" + cloth[14]);
		System.out.println("Index point 16:" + cloth[15]);
		System.out.println("Index point 17:" + cloth[16]);
        System.out.println("Index point 18:" + cloth[17]);
		System.out.println("Index point 19:" + cloth[18]);
		System.out.println("Index point 20:" + cloth[19]);
	    System.out.println("Index point 21:" + cloth[20]);
        System.out.println("Index point 22:" + cloth[21]);
		System.out.println("Index point 23:" + cloth[22]);
		System.out.println("Index point 24:" + cloth[23]);
		System.out.println("Index point 25:" + cloth[24]);
	}
}
class Locations{
	public static void main(String[] args){
		String[] Locations ={"India","New York","Los Angeles","London","Paris","Toronto","Cape Town",
		"Paris","Tokyo","Dubai","Sydney","Moscow","Bangkok","Amsterdam","Singapore","Rome","Hong Kong","Manila","America","Malasia"};
		
		System.out.println("Index point 1:" + Locations[0]);
		System.out.println("Index point 2:" + Locations[1]);
		System.out.println("Index point 3:" + Locations[2]);
		System.out.println("Index point 4:" + Locations[3]);
		System.out.println("Index point 5:" + Locations[4]);
		System.out.println("Index point 6:" + Locations[5]);
		System.out.println("Index point 7:" + Locations[6]);
		System.out.println("Index point 8:" + Locations[7]);
		System.out.println("Index point 9:" + Locations[8]);
		System.out.println("Index point 10:" + Locations[9]);
		System.out.println("Index point 11:" + Locations[10]);
		System.out.println("Index point 12" + Locations[11]);
		System.out.println("Index point 13:" + Locations[12]);
	    System.out.println("Index point 14:" + Locations[13]);
		System.out.println("Index point 15:" + Locations[14]);
		System.out.println("Index point 16:" + Locations[15]);
		System.out.println("Index point 17:" + Locations[16]);
		System.out.println("Index point 18:" + Locations[17]);
		System.out.println("Index point 19:" + Locations[18]);
		System.out.println("Index point 20:" + Locations[19]);
		System.out.println("-------------------------------");
		Locations[0]="Mandya";
		Locations[1] = "Bengaluru";
		Locations[2]="Mysuru";
		Locations[3]="Hubballi";
		Locations[4]="Belagavi";
		Locations[5]="Shivamogga"; 
        Locations[6]="Mangaluru";
		Locations[7]="Ballari";
		Locations[8]="Davangere";
		Locations[9]="Udupi";
		Locations[10]="Tumakuru";
        Locations[11]="Vijayapura";
		Locations[12]="Kalaburagi";
		Locations[13]="Chikkamagaluru";
		Locations[14]="Hassan";
		Locations[15]="Raichur";
        Locations[16]="Bagalkot";
		Locations[17]="Bidar";
		Locations[18]="Kolar";
		Locations[19]="Chitradurga";
		System.out.println("Index point 1:" + Locations[0]);
		System.out.println("Index point 2:" + Locations[1]);
		System.out.println("Index point 3:" + Locations[2]);
		System.out.println("Index point 4:" + Locations[3]);
		System.out.println("Index point 5:" + Locations[4]);
		System.out.println("Index point 6:" + Locations[5]);
		System.out.println("Index point 7:" + Locations[6]);
		System.out.println("Index point 8:" + Locations[7]);
		System.out.println("Index point 9:" + Locations[8]);
		System.out.println("Index point 10:" + Locations[9]);
		System.out.println("Index point 11:" + Locations[10]);
		System.out.println("Index point 12" + Locations[11]);
		System.out.println("Index point 13:" + Locations[12]);
	    System.out.println("Index point 14:" + Locations[13]);
		System.out.println("Index point 15:" + Locations[14]);
		System.out.println("Index point 16:" + Locations[15]);
		System.out.println("Index point 17:" + Locations[16]);
		System.out.println("Index point 18:" + Locations[17]);
		System.out.println("Index point 19:" + Locations[18]);
		System.out.println("Index point 20:" + Locations[19]);
	}
}
class Shoes{
	public static void main(String[] args){
		String[] Shoes={"Bata", "Paragon", "Liberty", "Relaxo", "Lakhani", 
            "Red Chief", "Khadim's", "Metro Shoes", "Action Shoes", "VKC Pride",
            "Campus", "Asian Footwear", "Woodland", "Sparx", "Lee Cooper",
            "Nike India", "Adidas India", "Puma India", "Reebok India", "Lancer",
            "HRX", "Furo Sports", "Power", "Mochi"};
		System.out.println("Index point 1:"+ Shoes[0]);
		System.out.println("Index point 2:" + Shoes[1]);
		System.out.println("Index point 3:" + Shoes[2]);
		System.out.println("Index point 4:" + Shoes[3]);
		System.out.println("Index point 5:" + Shoes[4]);
		System.out.println("Index point 6:" + Shoes[5]);
		System.out.println("Index point 7:" + Shoes[6]);
		System.out.println("Index point 8:" + Shoes[7]);
		System.out.println("Index point 9:" + Shoes[8]);
		System.out.println("Index point 10:" + Shoes[9]);
		System.out.println("Index point 11:" + Shoes[10]);
		System.out.println("Index point 12" + Shoes[11]);
		System.out.println("Index point 13:" + Shoes[12]);
	    System.out.println("Index point 14:" + Shoes[13]);
		System.out.println("Index point 15:" + Shoes[14]);
		System.out.println("Index point 16:" + Shoes[15]);
		System.out.println("Index point 17:" + Shoes[16]);
		System.out.println("Index point 18:" + Shoes[17]);
		System.out.println("Index point 19:" +Shoes[18]);
		System.out.println("Index point 20:" + Shoes[19]);
		System.out.println("Index point 21:"+ Shoes[20]);
		System.out.println("Index point 22:" + Shoes[21]);
		System.out.println("Index point 23:" + Shoes[22]);
		System.out.println("Index point 24:" + Shoes[23]);
		System.out.println("-------------------------------");
		Shoes[0] = "Red Tape";
		Shoes[1] ="Skechers India";
		Shoes[2] ="Wildcraft"; 
		Shoes[3] ="Fila India"; 
		Shoes[4] ="Asics";
        Shoes[5] = "Hush Puppies";
		Shoes[6] = "John Players Footwear";
		Shoes[7] = "Crocs India";
		Shoes[8] ="Zudio Shoes";
		Shoes[9] ="Neeman's";
        Shoes[10] = "Blackberrys";
		Shoes[11] ="Provogue";
		Shoes[12] ="UCB Shoes";
		Shoes[13] ="Louis Philippe Shoes";
		Shoes[14] ="Van Heusen Shoes";
        Shoes[15] ="Allen Solly Footwear";
		Shoes[16] ="Peter England Shoes";
		Shoes[17] ="Carlton London";
		Shoes[18] ="Tresmode";
		Shoes[19] ="Arrow Shoes";
        Shoes[20] = "Aldo India";
		Shoes[21] ="Steve Madden India";
		Shoes[22] ="Bridlen";
		Shoes[23] ="Avventura";
		System.out.println("Index point 1:"+ Shoes[0]);
		System.out.println("Index point 2:" + Shoes[1]);
		System.out.println("Index point 3:" + Shoes[2]);
		System.out.println("Index point 4:" + Shoes[3]);
		System.out.println("Index point 5:" + Shoes[4]);
		System.out.println("Index point 6:" + Shoes[5]);
		System.out.println("Index point 7:" + Shoes[6]);
		System.out.println("Index point 8:" + Shoes[7]);
		System.out.println("Index point 9:" + Shoes[8]);
		System.out.println("Index point 10:" + Shoes[9]);
		System.out.println("Index point 11:" + Shoes[10]);
		System.out.println("Index point 12" + Shoes[11]);
		System.out.println("Index point 13:" + Shoes[12]);
	    System.out.println("Index point 14:" + Shoes[13]);
		System.out.println("Index point 15:" + Shoes[14]);
		System.out.println("Index point 16:" + Shoes[15]);
		System.out.println("Index point 17:" + Shoes[16]);
		System.out.println("Index point 18:" + Shoes[17]);
		System.out.println("Index point 19:" +Shoes[18]);
		System.out.println("Index point 20:" + Shoes[19]);
		System.out.println("Index point 21:"+ Shoes[20]);
		System.out.println("Index point 22:" + Shoes[21]);
		System.out.println("Index point 23:" + Shoes[22]);
		System.out.println("Index point 24:" + Shoes[23]);
	}
}
class Cereals{
	public static void main(String[] args){
		String[] Cereals = {"Wheat", "Rice", "Maize", "Barley", "Oats",
            "Rye", "Millet", "Sorghum", "Quinoa", "Teff",
            "Fonio", "Triticale", "Spelt", "Buckwheat", "Kamut",
            "Farro", "Einkorn", "Amaranth", "Freekeh", "Durum Wheat"};
	    System.out.println("Index point 1:"+ Cereals[0]);
		System.out.println("Index point 2:" + Cereals[1]);
		System.out.println("Index point 3:" + Cereals[2]);
		System.out.println("Index point 4:" + Cereals[3]);
		System.out.println("Index point 5:" + Cereals[4]);
		System.out.println("Index point 6:" + Cereals[5]);
		System.out.println("Index point 7:" + Cereals[6]);
		System.out.println("Index point 8:" + Cereals[7]);
		System.out.println("Index point 9:" + Cereals[8]);
		System.out.println("Index point 10:" + Cereals[9]);
		System.out.println("Index point 11:" + Cereals[10]);
		System.out.println("Index point 12" + Cereals[11]);
		System.out.println("Index point 13:" + Cereals[12]);
	    System.out.println("Index point 14:" + Cereals[13]);
		System.out.println("Index point 15:" + Cereals[14]);
		System.out.println("Index point 16:" + Cereals[15]);
		System.out.println("Index point 17:" + Cereals[16]);
		System.out.println("Index point 18:" + Cereals[17]);
		System.out.println("Index point 19:" + Cereals[18]);
		System.out.println("Index point 20:" + Cereals[19]);
		System.out.println("------------------------------");
		Cereals[0] ="Wild Rice";
		Cereals[1] ="Brown Rice"; 
		Cereals[2] ="Bulgur"; 
		Cereals[3] ="Emmer"; 
		Cereals[4] ="Finger Millet";
        Cereals[5] ="Pearl Millet"; 
	    Cereals[6] ="Little Millet";
		Cereals[7] ="Kodo Millet"; 
		Cereals[8] ="Foxtail Millet"; 
		Cereals[9] ="Barnyard Millet";
        Cereals[10] ="Red Rice"; 
		Cereals[11] ="Black Rice"; 
		Cereals[12] ="Sticky Rice"; 
		Cereals[13] ="Puffed Rice"; 
		Cereals[14] ="Cornflakes";
        Cereals[15] ="Chia Seeds"; 
		Cereals[16] ="Flax Seeds"; 
		Cereals[17] ="Sprouted Wheat"; 
		Cereals[18] ="Multigrain Mix"; 
		Cereals[19] ="Organic Quinoa";
		System.out.println("Index point 1:"+ Cereals[0]);
		System.out.println("Index point 2:" + Cereals[1]);
		System.out.println("Index point 3:" + Cereals[2]);
		System.out.println("Index point 4:" + Cereals[3]);
		System.out.println("Index point 5:" + Cereals[4]);
		System.out.println("Index point 6:" + Cereals[5]);
		System.out.println("Index point 7:" + Cereals[6]);
		System.out.println("Index point 8:" + Cereals[7]);
		System.out.println("Index point 9:" + Cereals[8]);
		System.out.println("Index point 10:" + Cereals[9]);
		System.out.println("Index point 11:" + Cereals[10]);
		System.out.println("Index point 12" + Cereals[11]);
		System.out.println("Index point 13:" + Cereals[12]);
	    System.out.println("Index point 14:" + Cereals[13]);
		System.out.println("Index point 15:" + Cereals[14]);
		System.out.println("Index point 16:" + Cereals[15]);
		System.out.println("Index point 17:" + Cereals[16]);
		System.out.println("Index point 18:" + Cereals[17]);
		System.out.println("Index point 19:" + Cereals[18]);
		System.out.println("Index point 20:" + Cereals[19]);
	}
}